HoynetConfig:
  mode: "training"
  device: "cpu"
  models:
    pcrn:
      data:
        codeFile: "./data/NASDAQ_FC_STK_IEM_IFO.csv"
        priceFile: "./data/data_2.csv"
      train:
        epochs: 500
        batches: 30
        lr: 0.0001
        eval: 0.2
        ckpt: ./checkpoints
      config:
        term: 300
        inputs: ["Open", "High", "Low", "Close", "Volume"]
        outputs: ["Open", "Close"]
        hiddens: 64
        nlayers: 7
        fusions: 32
        embeddings: 10,10
      # models: path....
    fin2vec:
      #models: fin2vec pretrained model이 있을 때
      encoder: # pcrn pretrained 값을 넣어야 함
      pcrn:
        data:
          codeFile: "./data/NASDAQ_FC_STK_IEM_IFO.csv"
          priceFile: "./data/data_2.csv"
        config:
          term: 300
          inputs: ["Open", "High", "Low", "Close", "Volume"]
          outputs: ["Open", "Close"]
          hiddens: 64
          nlayers: 7
          fusions: 32
          embeddings: 10,10
      d2v:
        config:
          type_: "finance"
          device: "cpu"
          embed_dim: 10
          ema_decay: 0.999
          ema_end_decay: 0.9999
          ema_anneal_end_step: 30000
      config:
        ncodes:
        outputs:
        d_model:
        nhead:
        d_hid:
        nlayers:
        dropout:
      train:
        epochs: 500
        batches: 30
        lr: 0.0001
        eval: 0.2
        ckpt: ./checkpoints
