train:
  device: cpu
  target: ./train0/config/pcrn.yml
  data: 
    codeFile : ../crawling/NASDAQ_FC_STK_IEM_IFO.csv
    priceFile : ../crawling/NASDAQ/E_NASDAQ_DATA.csv
  epochs: 50
  batches: 5
  lr: 0.0001
  trainRate: 0.8
  ckpt: ./train0/ckpt # path to checkpoint