fin2vec:
  ncode : 3000
  embeddings: 10,10
  d_model: 64
  nhead: 8
  d_hid: 64
  outputs: 32
  nlayers: 2 
  dropout: 0.2
  type_: finance
  data: ./data/data_2.csv
  # weight: .pth
  encoder: ./demo/config/pcrn.yml
